<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span></li><li><span><a href="#Examining-Data-for-Potential-Issues" data-toc-modified-id="Examining-Data-for-Potential-Issues-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Examining Data for Potential Issues</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Missing Values</a></span><ul class="toc-item"><li><span><a href="#Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values" data-toc-modified-id="Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Show the number of null values only of the columns that actually have null values</a></span></li><li><span><a href="#Remove-the-columns-that-have-more-than-10,000-null-values-in-them" data-toc-modified-id="Remove-the-columns-that-have-more-than-10,000-null-values-in-them-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Remove the columns that have more than 10,000 null values in them</a></span></li><li><span><a href="#Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null." data-toc-modified-id="Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Create a new dataframe that shows only the row where <code>displ</code> is null.</a></span></li><li><span><a href="#Fill-nan-values-with-the-most-appropriate-technique" data-toc-modified-id="Fill-nan-values-with-the-most-appropriate-technique-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Fill nan values with the most appropriate technique</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Incorrect-Values" data-toc-modified-id="Incorrect-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Incorrect Values</a></span><ul class="toc-item"><li><span><a href="#Check-similar-rows" data-toc-modified-id="Check-similar-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Check similar rows</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Low-Variance-Columns" data-toc-modified-id="Low-Variance-Columns-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Low Variance Columns</a></span><ul class="toc-item"><li><span><a href="#Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame." data-toc-modified-id="Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame.-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.</a></span></li></ul></li><li><span><a href="#Extreme-Values-and-Outliers" data-toc-modified-id="Extreme-Values-and-Outliers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extreme Values and Outliers</a></span></li><li><span><a href="#Data-Type-Correction" data-toc-modified-id="Data-Type-Correction-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Type Correction</a></span><ul class="toc-item"><li><span><a href="#Check-the-data-type-of-each-column" data-toc-modified-id="Check-the-data-type-of-each-column-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Check the data type of each column</a></span></li><li><span><a href="#Cleaning-years" data-toc-modified-id="Cleaning-years-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cleaning years</a></span></li></ul></li><li><span><a href="#Cleaning-Text-and-Removing-Special-Characters" data-toc-modified-id="Cleaning-Text-and-Removing-Special-Characters-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Cleaning Text and Removing Special Characters</a></span></li><li><span><a href="#Finding-and-Removing-Duplicates" data-toc-modified-id="Finding-and-Removing-Duplicates-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Finding and Removing Duplicates</a></span><ul class="toc-item"><li><span><a href="#Drop-duplicate-rows-that-are-completely-equal" data-toc-modified-id="Drop-duplicate-rows-that-are-completely-equal-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Drop duplicate rows that are completely equal</a></span></li><li><span><a href="#Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns." data-toc-modified-id="Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns.-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.</a></span></li></ul></li><li><span><a href="#Export-clean-dataset" data-toc-modified-id="Export-clean-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Export clean dataset</a></span></li></ul></div>

# Data Cleaning


Lab Goals

+ Examine data for potential issues.
+ Identify and fill in missing values.
+ Identify and correct incorrect values.
+ Remove low variance columns.
+ Identify potential outliers.
+ Correct incorrect data types.
+ Remove special characters and clean categorical variables.
+ Identify and remove duplicate records.

Introduction

When working with data sets, you will find that they often require a bit of cleaning. Whether Pandas originally read the data types incorrectly, records are duplicated, the data contains special characters or missing value, or there are slightly different references to the same entity, every data analyst must know how to clean the data they are working with before analyzing it. In this lesson, you will learn about some of the most common problems that make data messy and methods for correcting those problems and cleaning your data.

The data set we are going to be using for this lesson is a messy version of the vehicles data set we worked with in the previous lesson. Let's import this version of our data set so that we can then practice cleaning it up.

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
#Load data from vehicles_messy.csv
pd.set_option('display.max_columns', None) 

data = pd.read_csv('../data/vehicles_messy.csv',low_memory=False)

# Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any **potential issues**. Some of the things we are interested in identifying in the data at this stage include:

- Missing values
- Special characters
- Incorrect values
- Extreme values or outliers
- Duplicate records
- Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand. We can start by visually inspecting the data using the `.head` method, which will show us the first 5 rows of data.

In [3]:
#your code
data.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

But how big actually is our dataframe??? Check it with `.shape` method

In [4]:
#your code
data.shape

(37843, 83)

Let's dive a little more in the content of our data set. Is there any method that shows us the **column names**, its **data types** and number of **non-null values**?

In [5]:
#your code
data.dtypes

barrels08     float64
barrelsA08    float64
charge120     float64
charge240     float64
city08          int64
               ...
modifiedOn     object
startStop      object
phevCity        int64
phevHwy         int64
phevComb        int64
Length: 83, dtype: object

In [6]:
data.value_counts

<bound method DataFrame.value_counts of        barrels08  barrelsA08  charge120  charge240  city08  city08U  cityA08  \
0      15.695714         0.0        0.0        0.0      19      0.0        0
1      29.964545         0.0        0.0        0.0       9      0.0        0
2      12.207778         0.0        0.0        0.0      23      0.0        0
3      29.964545         0.0        0.0        0.0      10      0.0        0
4      17.347895         0.0        0.0        0.0      17      0.0        0
...          ...         ...        ...        ...     ...      ...      ...
37838  14.982273         0.0        0.0        0.0      19      0.0        0
37839  14.330870         0.0        0.0        0.0      20      0.0        0
37840  15.695714         0.0        0.0        0.0      18      0.0        0
37841  15.695714         0.0        0.0        0.0      18      0.0        0
37842  18.311667         0.0        0.0        0.0      16      0.0        0

       cityA08U  cityCD  cityE  cityUF  co2  co2A  co2TailpipeAGpm  \
0           0.0     0.0    0.0     0.0   -1    -1              0.0
1           0.0     0.0    0.0     0.0   -1    -1              0.0
2           0.0     0.0    0.0     0.0   -1    -1              0.0
3           0.0     0.0    0.0     0.0   -1    -1              0.0
4           0.0     0.0    0.0     0.0   -1    -1              0.0
...         ...     ...    ...     ...  ...   ...              ...
37838       0.0     0.0    0.0     0.0   -1    -1              0.0
37839       0.0     0.0    0.0     0.0   -1    -1              0.0
37840       0.0     0.0    0.0     0.0   -1    -1              0.0
37841       0.0     0.0    0.0     0.0   -1    -1              0.0
37842       0.0     0.0    0.0     0.0   -1    -1              0.0

       co2TailpipeGpm  comb08  comb08U  combA08  combA08U  combE  combinedCD  \
0          423.190476      21      0.0        0       0.0    0.0         0.0
1          807.909091      11      0.0        0       0.0    0.0         0.0
2          329.148148      27      0.0        0       0.0    0.0         0.0
3          807.909091      11      0.0        0       0.0    0.0         0.0
4          467.736842      19      0.0        0       0.0    0.0         0.0
...               ...     ...      ...      ...       ...    ...         ...
37838      403.954545      22      0.0        0       0.0    0.0         0.0
37839      386.391304      23      0.0        0       0.0    0.0         0.0
37840      423.190476      21      0.0        0       0.0    0.0         0.0
37841      423.190476      21      0.0        0       0.0    0.0         0.0
37842      493.722222      18      0.0        0       0.0    0.0         0.0

       combinedUF  cylinders  displ                       drive  engId  \
0             0.0        4.0    2.0            Rear-Wheel Drive   9011
1             0.0       12.0    4.9            Rear-Wheel Drive  22020
2             0.0        4.0    2.2           Front-Wheel Drive   2100
3             0.0        8.0    5.2            Rear-Wheel Drive   2850
4             0.0        4.0    2.2  4-Wheel or All-Wheel Drive  66031
...           ...        ...    ...                         ...    ...
37838         0.0        4.0    2.2           Front-Wheel Drive  66030
37839         0.0        4.0    2.2           Front-Wheel Drive  66030
37840         0.0        4.0    2.2  4-Wheel or All-Wheel Drive  66030
37841         0.0        4.0    2.2  4-Wheel or All-Wheel Drive  66030
37842         0.0        4.0    2.2  4-Wheel or All-Wheel Drive  66031

         eng_dscr  feScore  fuelCost08  fuelCostA08 fuelType  \
0           (FFS)       -1        1600            0  Regular
1       (GUZZLER)       -1        3050            0  Regular
2           (FFS)       -1        1250            0  Regular
3             NaN       -1        3050            0  Regular
4      (FFS,TRBO)       -1        2150            0  Premium
...           ...      ...         ...          ...      ...
37838       (FFS)       -1        1500            0  Regular
37839       (FFS)       -1        1450            0  Regular
37840       (FFS)       -1        1600            0  Regular
37841       (FFS)       -1        1600            0  Regular
37842  (FFS,TRBO)       -1        2250            0  Premium

              fuelType1  ghgScore  ghgScoreA  highway08  highway08U  \
0      Regular Gasoline        -1         -1         25         0.0
1      Regular Gasoline        -1         -1         14         0.0
2      Regular Gasoline        -1         -1         33         0.0
3      Regular Gasoline        -1         -1         12         0.0
4      Premium Gasoline        -1         -1         23         0.0
...                 ...       ...        ...        ...         ...
37838  Regular Gasoline        -1         -1         26         0.0
37839  Regular Gasoline        -1         -1         28         0.0
37840  Regular Gasoline        -1         -1         24         0.0
37841  Regular Gasoline        -1         -1         24         0.0
37842  Premium Gasoline        -1         -1         21         0.0

       highwayA08  highwayA08U  highwayCD  highwayE  highwayUF  hlv  hpv  \
0               0          0.0        0.0       0.0        0.0    0    0
1               0          0.0        0.0       0.0        0.0    0    0
2               0          0.0        0.0       0.0        0.0   19   77
3               0          0.0        0.0       0.0        0.0    0    0
4               0          0.0        0.0       0.0        0.0    0    0
...           ...          ...        ...       ...        ...  ...  ...
37838           0          0.0        0.0       0.0        0.0    0    0
37839           0          0.0        0.0       0.0        0.0    0    0
37840           0          0.0        0.0       0.0        0.0    0    0
37841           0          0.0        0.0       0.0        0.0    0    0
37842           0          0.0        0.0       0.0        0.0    0    0

          id  lv2  lv4        make                model mpgData  phevBlended  \
0          1    0    0  Alfa Romeo   Spider Veloce 2000       Y        False
1         10    0    0     Ferrari           Testarossa       N        False
2        100    0    0       Dodge              Charger       Y        False
3       1000    0    0       Dodge  B150/B250 Wagon 2WD       N        False
4      10000    0   14      Subaru     Legacy AWD Turbo       N        False
...      ...  ...  ...         ...                  ...     ...          ...
37838   9995    0   14      Subaru               Legacy       N        False
37839   9996    0   14      Subaru               Legacy       N        False
37840   9997    0   14      Subaru           Legacy AWD       Y        False
37841   9998    0   14      Subaru           Legacy AWD       N        False
37842   9999    0   14      Subaru     Legacy AWD Turbo       N        False

       pv2  pv4  range  rangeCity  rangeCityA  rangeHwy  rangeHwyA  \
0        0    0      0        0.0         0.0       0.0        0.0
1        0    0      0        0.0         0.0       0.0        0.0
2        0    0      0        0.0         0.0       0.0        0.0
3        0    0      0        0.0         0.0       0.0        0.0
4        0   90      0        0.0         0.0       0.0        0.0
...    ...  ...    ...        ...         ...       ...        ...
37838    0   90      0        0.0         0.0       0.0        0.0
37839    0   90      0        0.0         0.0       0.0        0.0
37840    0   90      0        0.0         0.0       0.0        0.0
37841    0   90      0        0.0         0.0       0.0        0.0
37842    0   90      0        0.0         0.0       0.0        0.0

                 trany    UCity  UCityA  UHighway  UHighwayA           VClass  \
0         Manual 5-spd  23.3333     0.0   35.0000        0.0      Two Seaters
1         Manual 5-spd  11.0000     0.0   19.0000        0.0      Two Seaters
2         Manual 5-spd  29.0000     0.0   47.0000        0.0  Subcompact Cars
3      Automatic 3-spd  12.2222     0.0   16.6667        0.0             Vans
4         Manual 5-spd  21.0000     0.0   32.0000        0.0     Compact Cars
...                ...      ...     ...       ...        ...              ...
37838  Automatic 4-spd  24.0000     0.0   37.0000        0.0     Compact Cars
37839     Manual 5-spd  25.0000     0.0   39.0000        0.0     Compact Cars
37840  Automatic 4-spd  23.0000     0.0   34.0000        0.0     Compact Cars
37841     Manual 5-spd  23.0000     0.0   34.0000        0.0     Compact Cars
37842  Automatic 4-spd  20.0000     0.0   29.0000        0.0     Compact Cars

       year  youSaveSpend guzzler trans_dscr tCharger sCharger atvType  \
0      1985         -1250     NaN        NaN      NaN      NaN     NaN
1      1985         -8500       T        NaN      NaN      NaN     NaN
2      1985           500     NaN        SIL      NaN      NaN     NaN
3      1985         -8500     NaN        NaN      NaN      NaN     NaN
4      1993         -4000     NaN        NaN        T      NaN     NaN
...     ...           ...     ...        ...      ...      ...     ...
37838  1993          -750     NaN      CLKUP      NaN      NaN     NaN
37839  1993          -500     NaN        NaN      NaN      NaN     NaN
37840  1993         -1250     NaN      CLKUP      NaN      NaN     NaN
37841  1993         -1250     NaN        NaN      NaN      NaN     NaN
37842  1993         -4500     NaN      CLKUP        T      NaN     NaN

      fuelType2 rangeA evMotor mfrCode c240Dscr  charge240b c240bDscr  \
0           NaN    NaN     NaN     NaN      NaN         0.0       NaN
1           NaN    NaN     NaN     NaN      NaN         0.0       NaN
2           NaN    NaN     NaN     NaN      NaN         0.0       NaN
3           NaN    NaN     NaN     NaN      NaN         0.0       NaN
4           NaN    NaN     NaN     NaN      NaN         0.0       NaN
...         ...    ...     ...     ...      ...         ...       ...
37838       NaN    NaN     NaN     NaN      NaN         0.0       NaN
37839       NaN    NaN     NaN     NaN      NaN         0.0       NaN
37840       NaN    NaN     NaN     NaN      NaN         0.0       NaN
37841       NaN    NaN     NaN     NaN      NaN         0.0       NaN
37842       NaN    NaN     NaN     NaN      NaN         0.0       NaN

                          createdOn                    modifiedOn startStop  \
0      Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
1      Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
2      Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
3      Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
4      Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
...                             ...                           ...       ...
37838  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
37839  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
37840  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
37841  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN
37842  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013       NaN

       phevCity  phevHwy  phevComb
0             0        0         0
1             0        0         0
2             0        0         0
3             0        0         0
4             0        0         0
...         ...      ...       ...
37838         0        0         0
37839         0        0         0
37840         0        0         0
37841         0        0         0
37842         0        0         0

[37843 rows x 83 columns]>

In [7]:
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  int64
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(23)
memory usage: 59.8 MB

In [8]:
(~data.c240bDscr.isna()).sum()

36

# Missing Values

From this initial view, we can see that our data set contains some columns that have missing values in them and others that seem to have a lot of zero values. 

Let's see how prevalent missing values are in our data. We can use the Pandas `.isnull()` method to check whether the value in each field is missing (*null*) and return either True or False for each field. 

We can use the `.sum()` method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

## Show the number of null values only of the columns that actually have null values

In [9]:
#your code
nan_cols= data.isna().sum()
nan_cols[nan_cols>0].sort_values(ascending=False)

c240bDscr     37807
c240Dscr      37806
evMotor       37281
sCharger      37177
rangeA        36440
fuelType2     36435
guzzler       35562
atvType       34771
tCharger      32657
startStop     31705
mfrCode       30818
trans_dscr    22796
eng_dscr      15403
drive          1189
cylinders       123
displ           120
trany            11
dtype: int64

We can see that some columns have relatively few null values while others have tens of thousands of nulls. For fields that have a lot of null values, you will often have to make a judgement call. If you don't think the information is going to be very useful to your analysis, then you would remove those columns from your data frame.

## Remove the columns that have more than 10,000 null values in them

In Pandas, we can do that using the drop method. For our purposes, let's remove the columns that have more than 10,000 null values in them. We will add these column names to a list, and then we will pass those columns to the drop method and indicate that we want columns (not rows) dropped by setting the axis parameter to 1.

In [10]:
#your code
ls= ['c240bDscr','c240Dscr', 'evMotor', 'sCharger', 'rangeA', 'fuelType2', 'guzzler', 'atvType', 'tCharger', 'startStop', 'mfrCode', 'trans_dscr', 'eng_dscr' ]

data.drop(ls, axis=1, inplace=True)

In [11]:
#your code
nan_cols= data.isna().sum()
nan_cols[nan_cols>0].sort_values(ascending=False)

drive        1189
cylinders     123
displ         120
trany          11
dtype: int64

This leaves us with just a handful of remaining columns that have null values. Of the columns that remain, it looks like the cylinders column and the displ column have a similar number of nulls. Perhaps they are missing for similar reasons. We can investigate this by subsetting the data set and looking at just the records where displ is null and just the columns we think will be informative in allowing us to determine a reason.

## Create a new dataframe that shows only the row where `displ` is null. 
Keep only the columns you think are useful

In [12]:
data[(~(data.displ.isna()))].head()

#Así puedo ver donde no es nulo y por qué. Es un valor en litros, por esto los eléctricos no tienen ese valor

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [13]:
#your code
data_displ_null= data[data.displ.isna()]

In [14]:
data_displ_null.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.240,0.0,0.0,0.0,81,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,85,0.0,0,0.0,40.0,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0,0,0.0,0.0,37.0,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.282,0.0,0.0,0.0,81,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,72,0.0,0,0.0,47.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0,0,0.0,0.0,53.0,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.282,0.0,0.0,0.0,81,0.0,0,0.0,0.0,41.0,0.0,0,-1,0.0,0.0,72,0.0,0,0.0,47.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0,0,0.0,0.0,53.0,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.312,0.0,0.0,0.0,74,0.0,0,0.0,0.0,46.0,0.0,0,-1,0.0,0.0,65,0.0,0,0.0,52.0,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0,0,0.0,0.0,59.0,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.522,0.0,0.0,0.0,45,0.0,0,0.0,0.0,75.0,0.0,0,-1,0.0,0.0,39,0.0,0,0.0,87.0,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0,0,0.0,0.0,102.0,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0

In [15]:
data_displ_null.combinedUF.value_counts()

combinedUF
0.0    120
Name: count, dtype: int64

In [16]:
data_displ_null.fuelType1.value_counts()

fuelType1
Electricity         118
Regular Gasoline      2
Name: count, dtype: int64

In [17]:
data_displ_null.fuelType.value_counts()

fuelType
Electricity    118
Regular          2
Name: count, dtype: int64

In [18]:
ls= ['phevCity','phevHwy','phevComb','UHighwayA','rangeHwyA','rangeCityA','pv2','phevBlended', 'highwayUF','highwayCD',
     'highwayA08U','highwayA08', 'fuelCostA08', 'displ','combinedUF','combA08U','combA08', 'co2TailpipeAGpm','barrelsA08','charge120',
     'cityA08', 'cityCD', 'cityUF']

In [19]:
data_displ_null.drop(ls, axis=1, inplace=True)

data_displ_null.head()

C:\Users\Mjp\AppData\Local\Temp\ipykernel_5376\262763586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_displ_null.drop(ls, axis=1, inplace=True)

,barrels08,charge240,city08,city08U,cityA08U,cityE,co2,co2A,co2TailpipeGpm,comb08,comb08U,combE,combinedCD,cylinders,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv4,range,rangeCity,rangeHwy,trany,UCity,UCityA,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.240,0.0,81,0.0,0.0,41.0,0,-1,0.0,85,0.0,40.0,0.0,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,0,90,0.0,0.0,NaN,116.2069,0.0,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8143,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,17328,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.312,0.0,74,0.0,0.0,46.0,0,-1,0.0,65,0.0,52.0,0.0,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,0,29,0.0,0.0,NaN,105.3125,0.0,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

In [20]:
data_displ_null.shape

(120, 47)

## Fill nan values with the most appropriate technique 
*HINT: Electric cars do not have cylinders and can therefore not have any displacement*

In [21]:
#your code

nan_cols= data_displ_null.isna().sum()
nan_cols[nan_cols>0].sort_values(ascending=False)

cylinders    120
trany          9
drive          8
dtype: int64

In [22]:
data_displ_null.loc['cylinders']=0

C:\Users\Mjp\AppData\Local\Temp\ipykernel_5376\3926800529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_displ_null.loc['cylinders']=0

In [23]:
data_displ_null.head()

,barrels08,charge240,city08,city08U,cityA08U,cityE,co2,co2A,co2TailpipeGpm,comb08,comb08U,combE,combinedCD,cylinders,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv4,range,rangeCity,rangeHwy,trany,UCity,UCityA,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.240,0.0,81,0.0,0.0,41.0,0,-1,0.0,85,0.0,40.0,0.0,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,0,90,0.0,0.0,NaN,116.2069,0.0,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8143,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,17328,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.312,0.0,74,0.0,0.0,46.0,0,-1,0.0,65,0.0,52.0,0.0,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,0,29,0.0,0.0,NaN,105.3125,0.0,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

In [24]:
nan_cols= data_displ_null.isna().sum()
nan_cols[nan_cols>0].sort_values(ascending=False)

cylinders    120
trany          9
drive          8
dtype: int64

## Bonus: 
Now that we have filled in those null values, there are only two columns in the data set that still have null values: trany and drive. Use what you have learned in this section to investigate and potentially fill in the remaining null values.

In [25]:
#your code
data_displ_null.trany.value_counts()

trany
Automatic (A1)                      104
Automatic (variable gear ratios)      5
Manual 5-spd                          2
0                                     1
Name: count, dtype: int64

In [26]:
data_displ_null[(~(data_displ_null.trany.isna()))].head()

,barrels08,charge240,city08,city08U,cityA08U,cityE,co2,co2A,co2TailpipeGpm,comb08,comb08U,combE,combinedCD,cylinders,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv4,range,rangeCity,rangeHwy,trany,UCity,UCityA,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
21413,13.73375,0.0,22,0.0,0.0,0.0,-1,-1,370.291667,24,0.0,0.0,0.0,NaN,4-Wheel Drive,0,-1,1400,Regular,Regular Gasoline,-1,-1,28,0.0,0.0,0,0,29472,0,0,Subaru,RX Turbo,N,0,0,0.0,0.0,Manual 5-spd,27.4000,0.0,38.8000,Subcompact Cars,1985,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013
21414,14.33087,0.0,21,0.0,0.0,0.0,-1,-1,386.391304,23,0.0,0.0,0.0,NaN,4-Wheel Drive,0,-1,1450,Regular,Regular Gasoline,-1,-1,27,0.0,0.0,0,0,29473,0,0,Subaru,RX Turbo,N,0,0,0.0,0.0,Manual 5-spd,26.9000,0.0,37.1000,Subcompact Cars,1985,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013
23026,0.34800,0.0,62,0.0,0.0,54.0,0,-1,0.000000,58,0.0,58.0,0.0,NaN,2-Wheel Drive,0,-1,1150,Electricity,Electricity,-1,-1,54,0.0,63.0,0,0,30965,0,0,Ford,Ranger Pickup 2WD,N,0,50,0.0,0.0,Automatic (A1),88.6842,0.0,76.5909,Standard Pickup Trucks 2WD,2001,1000,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014
23027,0.34800,0.0,62,0.0,0.0,54.0,0,-1,0.000000,58,0.0,58.0,0.0,NaN,2-Wheel Drive,0,-1,1150,Electricity,Electricity,-1,-1,54,0.0,63.0,0,0,30966,0,0,Ford,Ranger Pickup 2WD,N,0,50,0.0,0.0,Automatic (A1),88.6842,0.0,76.5909,Standard Pickup Trucks 2WD,2000,1000,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014
23028,0.36000,0.0,59,0.0,0.0,57.0,0,-1,0.000000,56,0.0,60.0,0.0,NaN,2-Wheel Drive,0,-1,1150,Electricity,Electricity,-1,-1,52,0.0,64.0,0,0,30967,0,0,Ford,Ranger Pickup 2WD,N,0,65,0.0,0.0,Automatic (A1),84.2500,0.0,74.8889,Standard Pickup Trucks 2WD,2000,1000,0.0,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014

In [27]:
data_displ_null[data_displ_null.trany.isna()]

,barrels08,charge240,city08,city08U,cityA08U,cityE,co2,co2A,co2TailpipeGpm,comb08,comb08U,combE,combinedCD,cylinders,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv4,range,rangeCity,rangeHwy,trany,UCity,UCityA,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.240,0.0,81,0.0,0.0,41.0,0,-1,0.0,85,0.0,40.0,0.0,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,0,90,0.0,0.0,NaN,116.2069,0.0,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
7139,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,16424,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2000,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8143,0.282,0.0,81,0.0,0.0,41.0,0,-1,0.0,72,0.0,47.0,0.0,NaN,2-Wheel Drive,0,-1,900,Electricity,Electricity,-1,-1,64,0.0,53.0,0,0,17328,0,0,Toyota,RAV4 EV,N,0,88,0.0,0.0,NaN,116.2069,0.0,91.0811,Sport Utility Vehicle - 2WD,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.312,0.0,74,0.0,0.0,46.0,0,-1,0.0,65,0.0,52.0,0.0,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,0,29,0.0,0.0,NaN,105.3125,0.0,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8147,0.270,0.0,84,0.0,0.0,40.0,0,-1,0.0,75,0.0,45.0,0.0,NaN,NaN,0,-1,900,Electricity,Electricity,-1,-1,66,0.0,51.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,0,33,0.0,0.0,NaN,120.3571,0.0,93.6111,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
9212,0.258,0.0,87,0.0,0.0,39.0,0,-1,0.0,78,0.0,43.0,0.0,NaN,2-Wheel Drive,0,-1,850,Electricity,Electricity,-1,-1,69,0.0,49.0,0,0,18290,0,0,Toyota,RAV4 EV,N,0,95,0.0,0.0,NaN,124.8148,0.0,99.1176,Sport Utility Vehicle - 2WD,2002,2500,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
9213,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,18291,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2002,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
10329,0.258,0.0,87,0.0,0.0,39.0,0,-1,0.0,78,0.0,43.0,0.0,NaN,2-Wheel Drive,0,-1,850,Electricity,Electricity,-1,-1,69,0.0,49.0,0,0,19296,0,0,Toyota,RAV4 EV,N,0,95,0.0,0.0,NaN,124.8148,0.0,99.1176,Sport Utility Vehicle - 2WD,2003,2500,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

In [28]:
#Investigando descubrí que fue un coche creado sin caja de cambios y con una única marcha.

data_displ_null.loc[data_displ_null.model=='RAV4 EV']='Single-speed'

C:\Users\Mjp\AppData\Local\Temp\ipykernel_5376\707345178.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Single-speed' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_displ_null.loc[data_displ_null.model=='RAV4 EV']='Single-speed'
C:\Users\Mjp\AppData\Local\Temp\ipykernel_5376\707345178.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Single-speed' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_displ_null.loc[data_displ_null.model=='RAV4 EV']='Single-speed'

In [29]:
data_displ_null[data_displ_null.trany.isna()]

,barrels08,charge240,city08,city08U,cityA08U,cityE,co2,co2A,co2TailpipeGpm,comb08,comb08U,combE,combinedCD,cylinders,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayE,hlv,hpv,id,lv2,lv4,make,model,mpgData,pv4,range,rangeCity,rangeHwy,trany,UCity,UCityA,UHighway,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn
7138,0.24,0.0,81,0.0,0.0,41.0,0,-1,0.0,85,0.0,40.0,0.0,NaN,NaN,0,-1,800,Electricity,Electricity,-1,-1,91,0.0,37.0,0,0,16423,0,0,Nissan,Altra EV,N,0,90,0.0,0.0,NaN,116.2069,0.0,129.6154,Midsize Station Wagons,2000,2750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8144,0.312,0.0,74,0.0,0.0,46.0,0,-1,0.0,65,0.0,52.0,0.0,NaN,NaN,0,-1,1000,Electricity,Electricity,-1,-1,58,0.0,59.0,0,0,17329,0,0,Ford,Th!nk,N,0,29,0.0,0.0,NaN,105.3125,0.0,82.1951,Two Seaters,2001,1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8146,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2001,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
8147,0.27,0.0,84,0.0,0.0,40.0,0,-1,0.0,75,0.0,45.0,0.0,NaN,NaN,0,-1,900,Electricity,Electricity,-1,-1,66,0.0,51.0,0,0,17331,0,0,Nissan,Hyper-Mini,N,0,33,0.0,0.0,NaN,120.3571,0.0,93.6111,Two Seaters,2001,2250,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016
9213,0.522,0.0,45,0.0,0.0,75.0,0,-1,0.0,39,0.0,87.0,0.0,NaN,2-Wheel Drive,0,-1,1700,Electricity,Electricity,-1,-1,33,0.0,102.0,0,0,18291,0,0,Ford,Explorer USPS Electric,N,0,38,0.0,0.0,NaN,62.4074,0.0,46.8056,Sport Utility Vehicle - 2WD,2002,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016

In [30]:
data_displ_null.loc[data_displ_null.model=='Hyper-Mini', 'drive'] ='2-Wheel Drive'

In [31]:
data_displ_null.loc[data_displ_null.trany.isna()]='unknown'

# Incorrect Values

In addition to null values, we also want to try to identify any values that seem incorrect. For example, in the previous section, we learned that a vehicle without cylinders should not have displacement and vice versa. Let's check to see if there are any cases that violate these rules.

In [32]:
#your code
#Coches con nulos en cylinders y not null en displ
data[(data.cylinders.isna()) & (~(data.displ.isna()))]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
21506,18.311667,0.0,0.0,0.0,15,0.0000,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0000,0,0.0,0.0,0.0,0.0,NaN,1.3,Rear-Wheel Drive,0,-1,1850,0,Regular,Regular Gasoline,-1,-1,22,0.0000,0,0.0,0.0,0.0,0.0,0,0,29557,0,0,Mazda,RX-7,N,False,0,0,0,0.0000,0.0,0.0000,0.0,Manual 5-spd,19.0473,0.0,31.1094,0.0,Two Seaters,1986,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
28607,0.180000,0.0,0.0,7.0,126,126.3678,0,0.0,0.0,27.0,0.0,0,-1,0.0,0.000000,112,112.2077,0,0.0,30.0,0.0,0.0,NaN,0.0,Rear-Wheel Drive,141,10,600,0,Electricity,Electricity,10,-1,99,98.6914,0,0.0,0.0,34.0,0.0,13,85,36023,0,0,Mitsubishi,i-MiEV,N,False,0,0,62,68.5545,0.0,54.8184,0.0,Automatic (A1),180.5254,0.0,140.9876,0.0,Subcompact Cars,2016,3750,0.0,Fri Feb 06 00:00:00 EST 2015,Wed Apr 20 00:00:00 EDT 2016,0,0,0
29060,0.324000,0.0,0.0,6.0,61,61.3200,0,0.0,0.0,55.0,0.0,0,-1,0.0,0.000000,63,62.9357,0,0.0,54.0,0.0,0.0,NaN,0.0,Front-Wheel Drive,1,10,1050,0,Electricity,Electricity,10,-1,65,65.0300,0,0.0,0.0,52.0,0.0,0,0,36437,0,0,BYD,e6,N,False,0,0,127,121.1000,0.0,133.9000,0.0,Automatic (A1),87.6000,0.0,92.9000,0.0,Small Sport Utility Vehicle 2WD,2015,1500,0.0,Wed Jun 24 00:00:00 EDT 2015,Wed Jun 24 00:00:00 EDT 2015,0,0,0

In [33]:
#The other way around
data[(~(data.cylinders.isna())) & (data.displ.isna())]

Empty DataFrame
Columns: [barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, charge240b, createdOn, modifiedOn, phevCity, phevHwy, phevComb]
Index: []

Is there any row that seems to have strange values?

In [34]:
#your explanation here
#El primer registro, mazda RX-7 tiene un motor "wankel", que no tiene cilindros, así que le agrego cero

data.loc[(data.model=='RX-7')&(data.cylinders.isna()), 'cylinders']=0

In [35]:
#El segundo, el Mitsubishi, es eléctrico, por lo que no tiene cilindros 
#(lo que me hace pensar que debo evaluar los nulos de cilindrada en este dataFrame)

In [36]:
data[(data.cylinders.isna()) & (data.fuelType=='Electricity')]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
7138,0.240,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,85,0.0000,0,0.0,40.0000,0.0,0.0,NaN,NaN,NaN,0,-1,800,0,Electricity,Electricity,-1,-1,91,0.0000,0,0.0,0.0,37.0000,0.0,0,0,16423,0,0,Nissan,Altra EV,N,False,0,0,90,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,129.6154,0.0,Midsize Station Wagons,2000,2750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
7139,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,16424,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2000,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8143,0.282,0.0,0.0,0.0,81,0.0000,0,0.0,0.0,41.0000,0.0,0,-1,0.0,0.0,72,0.0000,0,0.0,47.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,900,0,Electricity,Electricity,-1,-1,64,0.0000,0,0.0,0.0,53.0000,0.0,0,0,17328,0,0,Toyota,RAV4 EV,N,False,0,0,88,0.0,0.0,0.0,0.0,NaN,116.2069,0.0,91.0811,0.0,Sport Utility Vehicle - 2WD,2001,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8144,0.312,0.0,0.0,0.0,74,0.0000,0,0.0,0.0,46.0000,0.0,0,-1,0.0,0.0,65,0.0000,0,0.0,52.0000,0.0,0.0,NaN,NaN,NaN,0,-1,1000,0,Electricity,Electricity,-1,-1,58,0.0000,0,0.0,0.0,59.0000,0.0,0,0,17329,0,0,Ford,Th!nk,N,False,0,0,29,0.0,0.0,0.0,0.0,NaN,105.3125,0.0,82.1951,0.0,Two Seaters,2001,1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
8146,0.522,0.0,0.0,0.0,45,0.0000,0,0.0,0.0,75.0000,0.0,0,-1,0.0,0.0,39,0.0000,0,0.0,87.0000,0.0,0.0,NaN,NaN,2-Wheel Drive,0,-1,1700,0,Electricity,Electricity,-1,-1,33,0.0000,0,0.0,0.0,102.0000,0.0,0,0,17330,0,0,Ford,Explorer USPS Electric,N,False,0,0,38,0.0,0.0,0.0,0.0,NaN,62.4074,0.0,46.8056,0.0,Sport Utility Vehicle - 2WD,2001,-1750,0.00,Tue Jan 01 00:00:00 EST 2013,Thu Jul 07 00:00:00 EDT 2016,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30969,0.192,0.0,0.0,4.0,120,119.6000,0,0.0,0.0,28.1744,0.0,0,-1,0.0,0.0,105,105.3754,0,0.0,31.9856,0.0,0.0,NaN,NaN,Front-Wheel Drive,37,10,600,0,Electricity,Electricity,10,-1,92,92.0000,0,0.0,0.0,36.6438,0.0,0,0,38168,0,19,Kia,Soul Electric,N,False,0,97,93,148.0,0.0,113.8,0.0,Automatic (A1),170.9000,0.0,131.4000,0.0,Small Station Wagons,2017,3750,0.00,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30972,0.204,0.0,0.0,10.0,98,97.5636,0,0.0,0.0,35.0000,0.0,0,-1,0.0,0.0,99,99.0945,0,0.0,34.0000,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0000,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5,0.0,214.8,0.0,Automatic (A1),132.2000,0.0,136.9000,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.192,0.0,0.0,12.0,101,101.4750,0,0.0,0.0,33.0000,0.0,0,-1,0.0,0.0,104,103.7678,0,0.0,32.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,21,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0000,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1,0.0,226.9,0.0,Automatic (A1),137.5000,0.0,144.6000,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.210,0.0,0.0,12.0,92,92.4713,0,0.0,0.0,36.0000,0.0,0,-1,0.0,0.0,98,97.5232,0,0.0,35.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,15,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0000,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9,0.0,346.9,0.0,Automatic (A1),125.3000,0.0,141.6000,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.216,0.0,0.0,12.0,91,91.2362,0,0.0,0.0,37.0000,0.0,0,-1,0.0,0.0,93,92.5663,0,0.0,36.0000,0.0,0.0,NaN,NaN,All-Wheel Drive,12,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0000,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5,0.0,203.2,0.0,Automatic (A1),124.3000,0.0,128.4000,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

In [37]:
data.loc[((data.cylinders.isna()) & (data.fuelType=='Electricity')),'cylinders']=0

Here we have identified a vehicle with a regular gasoline engine that reportedly does not have any cylinders but does have a value for displacement.

The way we would correct this would be to either perform some domain research or ask a domain expert to find out how many actual cylinders this vehicle had. Alternatively, you can also try to look at similar vehicles in the data set and determine the most likely value for this field.

## Check similar rows

In [38]:
#your code
data.loc[data.cylinders.isna()]

#Tiene 4 cilindros

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
21413,13.73375,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1400,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,29472,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,27.4,0.0,38.8,0.0,Subcompact Cars,1985,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
21414,14.33087,0.0,0.0,0.0,21,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1450,0,Regular,Regular Gasoline,-1,-1,27,0.0,0,0.0,0.0,0.0,0.0,0,0,29473,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,26.9,0.0,37.1,0.0,Subcompact Cars,1985,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

Suppose that using one of the aforementioned methods, we found out that this vehicle actually has a 4 cylinder engine. Update that specific value in the data frame.

In [39]:
#your code

data.loc[data.cylinders.isna(), 'cylinders']=4.0

## Bonus: 
 Try to find other values that might be incorrect in the data set based on what you know about automobiles and correct them.

In [40]:
#your code
#El subaru tiene 1.8 de displ

data.loc[data.cylinders.isna(), 'displ']=1.8

# Low Variance Columns

When analyzing data, we want the fields we are working with to be informative, and we will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

Let's try to identify columns where at least 90% of the values are the same so that we can remove them from our data set. To do this, we are going to create an empty list called low_variance that will eventually contain the names of columns that fit our criteria.

We will then write a for loop that will take the minimum and the 90th percentile value for all the numeric columns in our data set (identified via the _get_numeric_data method). If the 90th percentile and the minimum are equal to each other, that means that at least 90% of the values in that column are the same and we will append that column name to our low_variance list.

In [41]:
#your code
low_variance = []

for e in data._get_numeric_data():
    if (data[e].dtype=='bool'):
        continue    
    if (data[e].min()==data[e].quantile(0.9)):
        low_variance.append(e)

In [42]:
len(low_variance)

33

In [43]:
low_variance

['barrelsA08',
 'charge120',
 'charge240',
 'cityA08',
 'cityA08U',
 'cityCD',
 'cityE',
 'cityUF',
 'co2A',
 'co2TailpipeAGpm',
 'combA08',
 'combA08U',
 'combE',
 'combinedCD',
 'combinedUF',
 'fuelCostA08',
 'ghgScoreA',
 'highwayA08',
 'highwayA08U',
 'highwayCD',
 'highwayE',
 'highwayUF',
 'range',
 'rangeCity',
 'rangeCityA',
 'rangeHwy',
 'rangeHwyA',
 'UCityA',
 'UHighwayA',
 'charge240b',
 'phevCity',
 'phevHwy',
 'phevComb']

This returned 34 columns that we could potentially eliminate due to not having high enough variability to be informative. Of course, before we do this, we should check the values that do exist in these fields to confirm that they are not very informative. Once they have been checked, we can use the the drop method like we did earlier in this lesson to remove those columns from our data frame.

## Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.

In [44]:
#your code
data.drop(low_variance, axis=1, inplace=True)

In [45]:
data.shape

(37843, 37)

# Extreme Values and Outliers

Now that we have removed low variance columns, we should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

A common method for identifying outliers is one that leverages the interquartile range (IQR). Once the IQR is calculated, it is multiplied by a constant (typically 1.5) and lower and upper bounds are established at:

    25th Percentile - (IQR x 1.5)
    75th Percentile + (IQR x 1.5)

Any values outside this range are potential outliers and should be investigated.

Let's look at how we would do this for our data set using Python. We will use the Pandas describe function to easily calculate the 25th and 75th percentiles for every column and transpose the results so that we can easily reference the values in calculating the interquartile ranges.

In [46]:
#Run this code
stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats.head()

,count,mean,std,min,25%,50%,75%,max,IQR
barrels08,37843.0,17.532506,4.575950,0.06,14.33087,17.347895,20.600625,47.087143,6.269755
city08,37843.0,17.941389,6.660360,6.00,15.00000,17.000000,20.000000,138.000000,5.000000
city08U,37843.0,4.042737,9.645820,0.00,0.00000,0.000000,0.000000,138.304000,0.000000
co2,37843.0,61.503713,153.387715,-1.00,-1.00000,-1.000000,-1.000000,847.000000,0.000000
co2TailpipeGpm,37843.0,473.179736,122.188847,0.00,388.00000,467.736842,555.437500,1269.571429,167.437500

We will then create an empty data frame called outliers with the same columns as our data set. Finally, we will loop through each column in the data calculating the lower and upper bounds, retrieving records where the value for that column falls outside the bounds we established, and appending those results to our outlier data frame.

In [47]:
#Run this code
outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data[(data[col] < lower) | (data[col] > upper)].copy()
    results['Outlier'] = col
    

    #outliers = outliers.append(results)

In [48]:
results['Outlier'].value_counts()

Outlier
youSaveSpend    604
Name: count, dtype: int64

In [49]:
data.drop('youSaveSpend', axis=1, inplace=True)

Our outliers data frame should now be populated with records that you can investigate further and determine whether they should be kept in the data or dropped. The Outlier column we added before appending the results for the column to the outliers data frame will let you know what column in each record contained the outlier. If you find that this method is returning too many results, you can be more stringent with your cutoff criteria (e.g. increasing the constant by which you multiply the IQR to 3 instead of 1.5).

# Data Type Correction

One common problem that is often overlooked is incorrect data types. This typically occurs when there is a numeric variable that should actually be represented as a categorical variable.

## Check the data type of each column

In [50]:
##your code
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 36 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   barrels08       37843 non-null  float64
 1   city08          37843 non-null  int64
 2   city08U         37843 non-null  float64
 3   co2             37843 non-null  int64
 4   co2TailpipeGpm  37843 non-null  float64
 5   comb08          37843 non-null  int64
 6   comb08U         37843 non-null  float64
 7   cylinders       37843 non-null  float64
 8   displ           37723 non-null  float64
 9   drive           36654 non-null  object
 10  engId           37843 non-null  int64
 11  feScore         37843 non-null  int64
 12  fuelCost08      37843 non-null  int64
 13  fuelType        37843 non-null  object
 14  fuelType1       37843 non-null  object
 15  ghgScore        37843 non-null  int64
 16  highway08       37843 non-null  int64
 17  highway08U      37843 non-null  float64
 18  hlv             37843 non-null  int64
 19  hpv             37843 non-null  int64
 20  id              37843 non-null  int64
 21  lv2             37843 non-null  int64
 22  lv4             37843 non-null  int64
 23  make            37843 non-null  object
 24  model           37843 non-null  object
 25  mpgData         37843 non-null  object
 26  phevBlended     37843 non-null  bool
 27  pv2             37843 non-null  int64
 28  pv4             37843 non-null  int64
 29  trany           37832 non-null  object
 30  UCity           37843 non-null  float64
 31  UHighway        37843 non-null  float64
 32  VClass          37843 non-null  object
 33  year            37843 non-null  int64
 34  createdOn       37843 non-null  object
 35  modifiedOn      37843 non-null  object
dtypes: bool(1), float64(9), int64(16), object(10)
memory usage: 10.1+ MB

## Cleaning years
Do you think column year is a continuous variable? Would you change it onto another dtype?

In [51]:
#your code
data['year']= pd.to_datetime(data['year'])

You can apply this technique to any column whose data type you would like to change.

In [52]:
#your code
data['make']= data['make'].apply(str)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 36 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   barrels08       37843 non-null  float64
 1   city08          37843 non-null  int64
 2   city08U         37843 non-null  float64
 3   co2             37843 non-null  int64
 4   co2TailpipeGpm  37843 non-null  float64
 5   comb08          37843 non-null  int64
 6   comb08U         37843 non-null  float64
 7   cylinders       37843 non-null  float64
 8   displ           37723 non-null  float64
 9   drive           36654 non-null  object
 10  engId           37843 non-null  int64
 11  feScore         37843 non-null  int64
 12  fuelCost08      37843 non-null  int64
 13  fuelType        37843 non-null  object
 14  fuelType1       37843 non-null  object
 15  ghgScore        37843 non-null  int64
 16  highway08       37843 non-null  int64
 17  highway08U      37843 non-null  float64
 18  hlv             37843 non-null  int64
 19  hpv             37843 non-null  int64
 20  id              37843 non-null  int64
 21  lv2             37843 non-null  int64
 22  lv4             37843 non-null  int64
 23  make            37843 non-null  object
 24  model           37843 non-null  object
 25  mpgData         37843 non-null  object
 26  phevBlended     37843 non-null  bool
 27  pv2             37843 non-null  int64
 28  pv4             37843 non-null  int64
 29  trany           37832 non-null  object
 30  UCity           37843 non-null  float64
 31  UHighway        37843 non-null  float64
 32  VClass          37843 non-null  object
 33  year            37843 non-null  datetime64[ns]
 34  createdOn       37843 non-null  object
 35  modifiedOn      37843 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(9), int64(15), object(10)
memory usage: 10.1+ MB

# Cleaning Text and Removing Special Characters

The presence of special characters in our fields has the potential to make analyzing our data challenging. Imagine not being able to perform calculations on a numeric field because it was currently represented as an object data type due to the fact that it had a dollar sign ($) in it. 

Similarly, imagine having a categorical field where you could not group records that belong in the same group together because in one field you are grouping by, terms that refer to the same thing are sometimes hyphenated. In cases like this, it is necessary to remove special characters so that we can properly analyze the data.

In our vehicles data set, the trany field has several special characters (parentheses, hyphens, etc.). Check the unique values and clean the column.

hint: check the `replace` function

In [54]:
#your code
data.trany.value_counts()

trany
Automatic 4-spd                     11042
Manual 5-spd                         8311
Automatic 3-spd                      3151
Automatic (S6)                       2638
Manual 6-spd                         2429
Automatic 5-spd                      2184
Manual 4-spd                         1483
Automatic 6-spd                      1432
Automatic (S8)                        960
Automatic (S5)                        824
Automatic (variable gear ratios)      681
Automatic 7-spd                       663
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        233
Auto(AM7)                             160
Auto(AV-S6)                           145
Auto(AM6)                             110
Automatic (A1)                        109
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           77
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Manual 4-spd Doubled                   17
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Auto(L4)                                2
Auto(L3)                                2
Automatic (AM5)                         2
Auto (AV)                               2
Auto(A1)                                1
Automatic (AM6)                         1
Automatic 6spd                          1
Auto (AV-S8)                            1
Auto (AV-S6)                            1
Manual 5 spd                            1
Auto(AM-S9)                             1
Name: count, dtype: int64

In [55]:
#your code

velocidad= int(re.findall(r'-?\d+\.\d+|-?\d+', 'Auto (AV-S6) ')[0])

velocidad

6

In [56]:
#your code
def velocidad(string):
    string=str(string)
    if('Manual' in string):
        return int(re.findall('\d+', string)[0])
    return 0

In [57]:
velocidad(np.nan)

0

In [58]:
data['speeds'] = data.trany.apply(velocidad)

In [59]:
#your code

#Podría hacerse de forma más limpia usando la sección de la string 'spd' y así eliminar todos los automáticos que tienen velocidad
def limpiar_trany(string):
    string=str(string)
    if('Manual' in string):
        return 'Manual'
    elif('Auto' in string):
        return string
    return 'unknown'

In [60]:
data['trany']= data['trany'].apply(limpiar_trany)

In [61]:
data.trany.value_counts()

trany
Manual                              12389
Automatic 4-spd                     11042
Automatic 3-spd                      3151
Automatic (S6)                       2638
Automatic 5-spd                      2184
Automatic 6-spd                      1432
Automatic (S8)                        960
Automatic (S5)                        824
Automatic (variable gear ratios)      681
Automatic 7-spd                       663
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        233
Auto(AM7)                             160
Auto(AV-S6)                           145
Auto(AM6)                             110
Automatic (A1)                        109
Auto(AM-S6)                            92
Automatic 9-spd                        90
Auto(AV-S7)                            63
Automatic (S9)                         26
Auto(AV-S8)                            26
Auto(AM5)                              12
unknown                                11
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (A6)                          4
Automatic (AV)                          4
Auto(L4)                                2
Auto (AV)                               2
Auto(L3)                                2
Automatic (AM5)                         2
Auto (AV-S8)                            1
Automatic 6spd                          1
Auto (AV-S6)                            1
Automatic (AM6)                         1
Auto(A1)                                1
Auto(AM-S9)                             1
Name: count, dtype: int64

As you can see, we now have no special characters, consistent naming, and proper spacing. We started out with 47 unique values in this column, and using this technique, we were able to reduce the number of unique values to 39.



# Finding and Removing Duplicates

The final topic we are going to cover in this lab is how to identify and remove duplicate rows (or rows that refer to the same entity) in our data. When trying to identify duplicates, we will use the columns (or attributes) of the data to help us determine what entities are similar enough to be considered the same entity. We want to start with all the columns we currently have available to us and work our way toward a lesser number of attributes in an intuitive fashion. In this process, the act of dropping duplicated records is easy, but identifying the correct attributes for comparison and which records to drop is sometimes quite challenging.

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. 

Pandas provides us with the ability to do that via the `drop_duplicates method`.

## Drop duplicate rows that are completely equal

In [62]:
#your code
data.duplicated().any()

False

This tells us that there were no records that matched exactly across all columns. However, if we reduce the number of columns in our data that we are interested in, we can try again and have a higher likelihood of finding duplicate records.

## Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.

In [63]:
data.columns

Index(['barrels08', 'city08', 'city08U', 'co2', 'co2TailpipeGpm', 'comb08',
       'comb08U', 'cylinders', 'displ', 'drive', 'engId', 'feScore',
       'fuelCost08', 'fuelType', 'fuelType1', 'ghgScore', 'highway08',
       'highway08U', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make', 'model',
       'mpgData', 'phevBlended', 'pv2', 'pv4', 'trany', 'UCity', 'UHighway',
       'VClass', 'year', 'createdOn', 'modifiedOn', 'speeds'],
      dtype='object')

In [64]:
data_copia= data.copy()

In [65]:
#your code
borrar=['barrels08', 'city08', 'city08U', 'co2', 'co2TailpipeGpm', 'comb08',
       'comb08U', 'cylinders', 'displ', 'drive', 'engId', 'feScore',
       'fuelCost08', 'fuelType', 'fuelType1', 'ghgScore', 'highway08',
       'highway08U', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make', 'model',
        'mpgData', 'phevBlended', 'pv2', 'pv4']

data_copia.drop(borrar, axis=1, inplace=True)

In [66]:
#data_copia.duplicated().any()
data_copia.drop_duplicates(inplace=True)

In [67]:
print('Number of duplicate records dropped: ', data_copia.shape[0]- data.shape[0])

Number of duplicate records dropped:  -9474

With the reduced number of columns, we were able to identify and drop 885 duplicate records.

# Export clean dataset
Export your bright new clean dataset into a csv file and store it in data folder.

In [68]:
#your code
data.to_csv('../data/vehiculos_final.csv')